CREATE TABLE users(
   id SERIAL PRIMARY KEY,
   name CHARACTER VARYING,
   login CHARACTER VARYING UNIQUE,
   password CHARACTER VARYING,
   address CHARACTER VARYING,
   sex CHARACTER VARYING,
   comment CHARACTER VARYING
);

